### ISSUE TITLE
请教Sidebar的问题

### ISSUE THREAD

**Issue by junniao** [NLRX/Vue-Components-Library#2]
使用Sidebar递归组件，使用自己的数据就没什么问题，但是使用后台给的数据就出现了问题，点击一个菜单之后其余的子菜单全部展开了，体验很不好，请问是哪里出现了问题，求教。我是菜鸡
![bug](https://user-images.githubusercontent.com/46438504/64109825-12d06c80-cdb3-11e9-8f8c-615310c654c3.png)

**Comment by NLRX** [comment]
如果使用自己模拟的数据没问题，换成后台给的真实数据就有问题，那可能是数据结构构造上的问题，可以仔细对比一下两份数据的异同，抱歉，才看看这条issue
